# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a90bbbf11fc12c048c5e3ec9147de2dbc8f3e44115b9ae7a72a5f9059a0d0df5f6877f2c5362e395f0acdc561d58d83926f2f3e51205e9791a1779e518f1724

test:
  secret_key_base: d090d213455fabe4337c74f76ad2e35943ad5f5bf6faf1a929077b9df8ae5e5528fbc12809895df8ef1360388c1fb726deeb22f7091082c7a262e0fb035719b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
